name: browserless-helloworld

on: [push]

jobs:
  browserless-helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Run Browserless Chrome
        run: docker run -d --name test -p 3000:3000 browserless/chrome:1.57-chrome-stable
      - name: Sleep for 120 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'
      - name: docker ps -a
        run: |
          docker ps -a
          docker logs test
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: test local browserless response
        run: |
          curl -vLk http://localhost:3000
          node -v
          npm -v
          node
      - name: test local browserless response
        run: |
          cd browserless-helloworld
          node ./index.js
          cd -
