name: debug-deploy

on:
  push:
  workflow_dispatch:

jobs:
  debug-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: test local browserless response
        run: |
          ls -ltrR
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
