name: debug-deploy

on:
  push:
  workflow_dispatch:

jobs:
  debug-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: dist
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
