name: youtube-news-scrape

on:
  push:
  workflow_dispatch:

jobs:
  youtube-news-scrape:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
